### PR TITLE
feat(carflag/webhook): add carLabel

### PR DESCRIPTION
**Pull request by Jaccosf**
- Get the label of the car in the webhook instead of the hash

### CODE REVIEW

**Comment by therealknight** [comment]
I'm curious, would this change work for the weapons too? changing the hash value into a text value like "WEAPON_"

**Comment by Jaccosf** [comment]
> I'm curious, would this change work for the weapons too? changing the hash value into a text value like "WEAPON_"

Since this uses the native `GetDisplayNameFromVehicleModel`, it isn't possible, as far as I know.

**Comment by Blumlaut** [comment]
Tested working? 😄

**Comment by Jaccosf** [comment]
> Tested working? 😄

Of course! 😛

**Pull request merged**
